GET http://localhost:59111/states/
###

Get http://localhost:59111/states/2/
###

POST http://localhost:59111/districts/
Content-Type:application/json 

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###

GET http://localhost:59111/districts/2/
###

DELETE http://localhost:59111/districts/25/
###

PUT http://localhost:59111/districts/10/
Content-Type:application/json 

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###

GET http://localhost:59111/states/2/stats/ 
###

GET http://localhost:59111/districts/2/details/
